### ISSUE TITLE
Installing on Raspbian jessie

### ISSUE THREAD

**Issue by Kekec852** [coreybutler/node-linux#22]
Hi,

i have received an error starting a service on rasbian jessie:

```
install
Install!
(node) Buffer.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.
service monitorpi start
/opt/monitor/node_modules/node-linux/lib/systemv.js:273
          if (err) throw err;
                   ^

Error: Command failed: /bin/sh -c service monitorpi start
Failed to start monitorpi.service: Unit monitorpi.service failed to load: No such file or directory.

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

My code for installing is:

```javascript
var Service = require('node-linux').Service;
var args = process.argv.slice(2);
var svc = new Service({
    name: 'MonitorPI',
    description: 'MonitorPI Server',
    script: require('path').join(__dirname, 'app.js'),
    wait: 2,
    grow: .5,
    maxRestarts: 5,
    env: {
        name: "NODE_ENV",
        value: "production"
    }
});
console.log(args[0]);
if (args.length >= 1) {
    if (args[0] == 'install') {
        svc.on('install', function () {
            svc.start();
        });
        svc.install();
        console.log("Install!");
    } else if (args[0] == 'uninstall') {
        svc.on('uninstall', function () {
            console.log('Uninstall complete.');
            console.log('The service exists: ', svc.exists);
        });
        // Uninstall the service.
        svc.uninstall();
        console.log("Uninstall!");
    }
}
```

I have tried to move script from /etc/init.d/ to /lib/systemd/system and renamed it to have .service at the end.

then i received:

```
Failed to start monitorpi.service: Unit monitorpi.service failed to load: Bad message. See system logs and 'systemctl status monitorpi.service' for details.
```

Systemd log:
```
Nov 20 10:22:44 raspberrypi systemd[1]: Configuration file /lib/systemd/system/monitorpi.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Nov 20 10:22:44 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:43] Missing '='.
Nov 20 10:22:45 raspberrypi systemd[1]: Configuration file /lib/systemd/system/monitorpi.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:19] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:21] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:24] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:26] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:29] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:32] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:34] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:35] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:36] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:43] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:44] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:45] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:47] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:48] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:49] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:52] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:53] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:54] Assignment outside of section. Ignoring.
Nov 20 10:22:45 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:56] Invalid section header '[ $UID -eq "0" ] && LOCAL_VAR_RUN=/var/run # in case this script is run by root, override user setting'
Nov 20 10:22:55 raspberrypi systemd[1]: Configuration file /lib/systemd/system/monitorpi.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:19] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:21] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:24] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:26] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:29] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:32] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:34] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:35] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:36] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:43] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:44] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:45] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:47] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:48] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:52] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:53] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:54] Assignment outside of section. Ignoring.
Nov 20 10:22:55 raspberrypi systemd[1]: [/lib/systemd/system/monitorpi.service:56] Invalid section header '[ $UID -eq "0" ] && LOCAL_VAR_RUN=/var/run # in case this script is run by root, override user setting'
```

**Comment by Kekec852** [comment]
There is one more thing on wheezy same code works like it should.

**Comment by Kekec852** [comment]
Now i have tried to change mode of installing service from 'systemv' to 'systemd' now it install in to correct folder with correct name but in logs there is a same error like before

**Comment by Kekec852** [comment]
Found a problem on npm there is an old version of node-linux and it didn't work with jessie. ;)
