### ISSUE TITLE
systemv.js child_process.exec fails on RHEL6 and CentOS6

### ISSUE THREAD

**Issue by sellis** [coreybutler/node-linux#23]
Hi, I have a situation where the start and stop methods in systemv.js fail as follows on RHEL6 and CentOS6:

...
Running /etc/init.d/myservice start...
/path/to/node_modules/node-linux/lib/systemv.js:282
          if (err) throw err;
                         ^
Error: Command failed: /bin/sh -c /etc/init.d/myservice start
    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

When I print the err object it looks like this:
{ [Error: Command failed: /bin/sh -c /etc/init.d/myservice start]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /etc/init.d/myservice start' }

On CentOS7 the systemd.js code to start and stop the service with child_process.exec() works fine.

Has anyone else seen an issue like this or have any ideas?
Thanks,
Scott

**Comment by sellis** [comment]
I discovered that the problem was that /var/lock/subsys/node-daemon-myservice existed, which causes the start command to fail.

**Comment by sellis** [comment]
I discovered that the file /var/lock/subsys/node-daemon-myservice existed, which causes the start command to fail.

**Comment by sellis** [comment]
It appears since the init.d script calls kill -9  on the wrapper process (SIGKILL), the wrapper does not have a chance to run the exit handler and kill its child process, so the node app keeps running.

**Comment by sellis** [comment]
This is fixed in my pull request.

**Comment by sellis** [comment]
Fixed when pull request [#25](https://github.com/coreybutler/node-linux/pull/25) was merged.
