### ISSUE TITLE
Node 6.2.0 - Error

### ISSUE THREAD

**Issue by LeandroFavero** [coreybutler/node-linux#32]
Hi,

With Node 4.4.4 works very well. But in 6.2.0 happens this issue:

Installing in /home/ec2-user/Test forder...
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at new daemon (/home/ec2-user/Test/system/daemons/node-linux/lib/daemon.js:208:30)
    at Object.<anonymous> (/home/ec2-user/Test/install.js:10:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)

**Comment by myAlterX** [comment]
Hi!

Looking at the source code from daemon.js it is looking for a cwd property.
If you provide this in the configuration document you can get away with node 6.x

```
var svc = new Service({
  name: "servicename",
  description: "Service Description",
  script: "server.js",
  cwd: "/path/to/your/app/"
});
```

cheers!

**Comment by kekkokk** [comment]
is there any way to pass the cwd to the node process?

**Comment by coreybutler** [comment]
@kekkokk - there is now. I just merged a fix that allows the solution from @myAlterX to work properly. It's in version `0.1.11`.

**Comment by kekkokk** [comment]
maaany thanks
